---

- name: Copy over nginx.conf
  template: src=nginx.conf.j2 dest='/etc/nginx/nginx.conf'
  notify: restart nginx

- name: Disabled default domains
  file: path={{ item.path }} state={{ item.state }}
  with_items:
    - { path: '{{ nginx_vhost_path }}/default.conf', state: absent } 
    - { path: '{{ nginx_vhost_path }}/example_ssl.conf', state: absent }

- name: Setup default vhost
  template: src=default_vhost.conf.j2 dest={{ nginx_vhost_path }}/{{ domain }}.conf
  notify: restart nginx

- name: Add document root for custom domain
  file: dest='/var/www/vhosts/{{ domain }}' state=directory owner={{ nginx_user }} group={{ nginx_user }}
  when: domain != 'example.com'
  notify: restart nginx

- name: Enable and start service
  service: name=nginx state=started enabled=yes


