---

- name: Copy over nginx.conf
  template: src=nginx.conf.j2 dest='/etc/nginx/nginx.conf'
  notify: restart nginx

- name: Setup default vhost
  template: src=default_vhost.conf.j2 dest={{ nginx_vhost_path }}
  notify: restart nginx

- name: Add document root for custom domain
  file: dest='/var/www/vhosts/{{ domain }}' state=directory owner={{ nginx_user }} group={{ nginux_user }}
  when: domain != 'example.com'

- name: Enable and start service
  service: name=nginx state=started enabled=yes


