---
- hosts: all
  user: root

  tasks:
    - group_by: key={{ ansible_os_family }}


# Applies only to RedHat systems

- hosts: RedHat
  user: root
  gather_facts: false

  pre_tasks:
    - name: install LSB_release req for RHEL systems
      yum: pkg=redhat-lsb state=installed
      register: installed
    
    - name: regather facts
      setup: 
      when: installed|changed

#    - include_vars: group_vars/RHEL_7.yml
#      when: ansible_os_family == 'RedHat' and ansible_lsb.major_release == '7'
#      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]

  roles:
    - { role: nginx, tags: nginx }
    - { role: php-fpm, tags: php-fpm }


# Applies only to Debian systems

- hosts: Debian
  user: root
  gather_facts: false


#  pre_tasks:
#    - include_vars: group_vars/Ubuntu_14.yml
#      when: ansible_os_family == 'Debian' and ansible_lsb.release == '14.04'

  roles:
    - { role: nginx, tags: nginx }
    - { role: php-fpm, tags: php-fpm }

